// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineElectronicsStore.Data;

#nullable disable

namespace OnlineElectronicsStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250512184030_AddDecimalPrecisionToOrders")]
    partial class AddDecimalPrecisionToOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineElectronicsStore.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PC Components"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Peripherals"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audio Devices"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gaming Accessories"
                        });
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DiscountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountAmount = 10.00m,
                            DiscountCode = "WELCOME10",
                            ExpiryDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            DiscountAmount = 20.00m,
                            DiscountCode = "SUMMER20",
                            ExpiryDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            LongDescription = "A powerhouse machine featuring an NVIDIA RTX GPU, 16 GB RAM, and a 1 TB SSD—perfect for top-tier gaming and streaming.",
                            MainImageUrl = "/images/products/1-main.jpg",
                            Name = "Gaming Laptop",
                            Price = 1200m,
                            ShortDescription = "High-end gaming laptop with RTX graphics",
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            LongDescription = "An ultra-portable device with 14\" FHD display, 8 GB RAM, and long battery life—ideal for professionals on the move.",
                            MainImageUrl = "/images/products/2-main.jpg",
                            Name = "Business Laptop",
                            Price = 950m,
                            ShortDescription = "Lightweight, portable business laptop",
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            LongDescription = "Slim design with 11th Gen Intel Core, 512 GB SSD, and up to 12 hours battery life—great for travel and productivity.",
                            MainImageUrl = "/images/products/3-main.jpg",
                            Name = "UltraBook Pro",
                            Price = 1500m,
                            ShortDescription = "Compact and powerful ultrabook",
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            LongDescription = "Equipped with 8 GB GDDR6, DLSS support, and ray-tracing cores for ultra-realistic graphics in the latest games.",
                            MainImageUrl = "/images/products/4-main.jpg",
                            Name = "Graphics Card RTX 4070",
                            Price = 600m,
                            ShortDescription = "Next-gen graphics card for gaming",
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            LongDescription = "Offers 8 cores and 16 threads, up to 4.9 GHz Turbo Boost, and DDR5 memory support—ideal for gaming and content creation.",
                            MainImageUrl = "/images/products/5-main.jpg",
                            Name = "Intel i7 Processor",
                            Price = 400m,
                            ShortDescription = "12th Gen Intel Core i7 CPU",
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            LongDescription = "80 Plus Gold PSU with modular cables, Japanese capacitors, and silent fan for reliable, quiet performance.",
                            MainImageUrl = "/images/products/6-main.jpg",
                            Name = "750W Power Supply",
                            Price = 100m,
                            ShortDescription = "High-efficiency ATX power supply",
                            Stock = 40
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            LongDescription = "Durable switches with customizable RGB backlighting, programmable macros, and detachable wrist rest for comfort.",
                            MainImageUrl = "/images/products/7-main.jpg",
                            Name = "Mechanical Keyboard",
                            Price = 80m,
                            ShortDescription = "RGB mechanical gaming keyboard",
                            Stock = 50
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            LongDescription = "Adjustable DPI to 16,000, contoured shape, and up to 60 hours battery life—perfect for work or play.",
                            MainImageUrl = "/images/products/8-main.jpg",
                            Name = "Wireless Mouse",
                            Price = 25m,
                            ShortDescription = "Ergonomic 2.4 GHz wireless mouse",
                            Stock = 100
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            LongDescription = "27\" 3840×2160 panel with HDR10, 95% DCI-P3, and built-in speakers—great for design, gaming, and streaming.",
                            MainImageUrl = "/images/products/9-main.jpg",
                            Name = "27-inch 4K Monitor",
                            Price = 300m,
                            ShortDescription = "Ultra HD IPS display monitor",
                            Stock = 12
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            LongDescription = "6.1\" Super Retina XDR, A16 Bionic chip, Pro camera system with 48 MP main sensor, and Dynamic Island.",
                            MainImageUrl = "/images/products/10-main.jpg",
                            Name = "iPhone 14 Pro",
                            Price = 1100m,
                            ShortDescription = "Apple's flagship smartphone",
                            Stock = 20
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            LongDescription = "6.1\" AMOLED 2X, Snapdragon 8 Gen 2, triple-camera setup, 3900 mAh battery with 25 W charging.",
                            MainImageUrl = "/images/products/11-main.jpg",
                            Name = "Samsung Galaxy S23",
                            Price = 1000m,
                            ShortDescription = "Samsung flagship with Dynamic AMOLED",
                            Stock = 18
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            LongDescription = "6.3\" OLED, Google Tensor G2 chip, Magic Eraser, and 30 W fast charging.",
                            MainImageUrl = "/images/products/12-main.jpg",
                            Name = "Google Pixel 7",
                            Price = 850m,
                            ShortDescription = "Google’s AI-powered smartphone",
                            Stock = 15
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            LongDescription = "Industry-leading ANC, 30 h battery life, multi-device pairing, and hi-res audio support.",
                            MainImageUrl = "/images/products/13-main.jpg",
                            Name = "Sony WH-1000XM5",
                            Price = 300m,
                            ShortDescription = "Premium noise-cancelling headphones",
                            Stock = 22
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            LongDescription = "JBL Signature Sound, 12 h playtime, and IPX7 water resistance—ideal for outdoors.",
                            MainImageUrl = "/images/products/14-main.jpg",
                            Name = "JBL Bluetooth Speaker",
                            Price = 150m,
                            ShortDescription = "Portable waterproof speaker",
                            Stock = 35
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            LongDescription = "7.1 virtual surround, noise-cancelling mic, memory foam earcups, USB/3.5 mm connectivity.",
                            MainImageUrl = "/images/products/15-main.jpg",
                            Name = "Gaming Headset",
                            Price = 70m,
                            ShortDescription = "Over-ear RGB gaming headset",
                            Stock = 40
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            LongDescription = "Realistic force feedback, pedal set with clutch, and adjustable angle—perfect for sims.",
                            MainImageUrl = "/images/products/16-main.jpg",
                            Name = "Racing Wheel Controller",
                            Price = 250m,
                            ShortDescription = "Force-feedback racing wheel",
                            Stock = 5
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            LongDescription = "Dynamic lighting, non-slip rubber bottom, and smooth surface for precise control.",
                            MainImageUrl = "/images/products/17-main.jpg",
                            Name = "RGB Mousepad",
                            Price = 30m,
                            ShortDescription = "Customizable RGB mousepad for gamers",
                            Stock = 80
                        });
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.ProductPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPhotos");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.ShippingDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("ShippingDetails");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            FullName = "Admin User",
                            Password = "Admin@123",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            Password = "User@123",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.CartItem", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Order", null)
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineElectronicsStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineElectronicsStore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Discount", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Invoice", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Order", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.OrderItem", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Order", "ParentOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineElectronicsStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Payment", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Product", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.ProductPhoto", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Review", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineElectronicsStore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.ShippingDetails", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Wishlist", b =>
                {
                    b.HasOne("OnlineElectronicsStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineElectronicsStore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Order", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OnlineElectronicsStore.Models.Product", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
